# Generated by Django 3.0.8 on 2020-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('sel1', models.CharField(max_length=50)),
                ('sel2', models.CharField(max_length=50)),
            ],
        ),
    ]
